AWSTemplateFormatVersion: 2010-09-09
Description: Deploys CloudBees Core into an existing Kubernetes cluster (qs-1pipqrqje)

Parameters:
  # KubeManifestLambdaArn:
  #   Type: String
  KubeGetLambdaArn:
    Type: String
  HelmLambdaArn:
    Type: String
  KubeConfigPath:
    Type: String
  KubeConfigKmsContext:
    Type: String
  StorageClassName:
    Type: String
  CustomValueYaml:
    Type: String

Resources:
  NginxIngressController:
    Type: "Custom::Helm"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      Name: nginx-ingress
      Namespace: nginx-ingress
      Chart: stable/nginx-ingress
      Values:
        rbac.create: true
        controller.service.externalTrafficPolicy: Local
  IngressHostName:
    DependsOn: NginxIngressController
    Type: "Custom::KubeGet"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref KubeGetLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      Namespace: nginx-ingress
      Name: !Sub 'svc/${NginxIngressController.Service0}'
      JsonPath: '{.status.loadBalancer.ingress[0].hostname}'
  CloudBeesCore:
    Type: "Custom::Helm"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      RepoUrl: https://charts.cloudbees.com/public/cloudbees
      Chart: cloudbees/cloudbees-core
      Version: 3.8.0+a0d07461ae1c
      Name: cloudbees-core
      Namespace: cloudbees-core
      ValueYaml: !Sub |
        nginx-ingress:
          Enabled: false
        OperationsCenter:
          HostName: ${IngressHostName}
          Platform: eks
          ExtraConfigMaps:
          - name: cloudbees-referrer
            labels:
              app.kubernetes.io/component: trial-telemetry
            data:
              .cloudbees-referrer.txt: |
                Core on AWS Quick Start
          ExtraVolumes:
            - name: cloudbees-referrer
              configMap:
                name:  cloudbees-referrer
          ExtraVolumeMounts:
          - name: cloudbees-referrer
            mountPath: /var/jenkins_home/.cloudbees-referrer.txt
            subPath: .cloudbees-referrer.txt
            readOnly: true
        Persistence:
          StorageClass: ${StorageClassName}
        NetworkPolicy:
          ingressControllerSelector:
            - namespaceSelector:
                matchLabels:
                  name: nginx-ingress
              podSelector:
                matchLabels:
                  app: nginx-ingress
                  component: controller
      CustomValueYaml: !Ref CustomValueYaml

Outputs:
  CloudBeesJenkinsOperationsCenterUrl:
    Value: !Sub "http://${IngressHostName}/cjoc"
  #InitialAdminPassword: requires `Custom::KubeExec` or similar
